# motion def:
motion_file: allan_variance_analysis.csv
# IMU params:
imu: 1
# sample frequency of simulated GNSS/IMU data:
sample_frequency:
    imu: 100.0
    gps: 10.0
# topic name:
topic_name: /sim/sensor/imu
# output rosbag path:
output_path: /Users/zachary/Desktop/sensor-fusion-for-localization-and-mapping/workspace/data/gnss_ins_sim/allan_variance_analysis
# output name:
output_name: data.bag